---
- name: Check apache conf
  command: "/usr/sbin/apachectl configtest"
  become: true
  listen: "Restart apache"

- name: Restart Apache service
  service:
    name: apache2
    state: restarted
  listen: "Restart apache"
