---

- name: Install nginx
  package:
    name:
      - nginx

- name: Copy unauthorized.png
  copy:
    src: unauthorized.png
    dest: /var/www/html/

- name: Remove nginx default config
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: "Restart nginx"

