---
- name: Install Influxdb
  apt:
    name:
      - python3-influxdb
      - influxdb
      - influxdb-client
    state: present

- name: Create Influx database
  community.general.influxdb_database:
      hostname: "localhost"
      database_name: "{{ influxdb_database }}"

- name: Create a user on localhost using default login credentials
  community.general.influxdb_user:
    admin: yes
    user_name: "{{ influxdb_username }}"
    user_password: "{{ influxdb_password }}"
    grants:
      - database: '{{ influxdb_database }}'
        privilege: 'WRITE'
      - database: '{{ influxdb_database }}'
        privilege: 'READ'

- name: Install influx config
  template:
    src: "{{ item }}"
    dest: /etc/influxdb/
  with_items:
    - influxdb.conf
  notify: Restart influxdb

- name: Install apache files
  template:
    src: "{{ item }}"
    dest: /etc/apache2/sites-enabled/influxdb-proxy.conf
  with_items:
    - apache.conf
  notify: Restart apache

