---
- name: Install Influxdb
  apt:
    name:
      - python3-influxdb
      - influxdb
      - influxdb-client
    state: present

- name: Create Influx database
  community.general.influxdb_database:
      hostname: "localhost"
      database_name: "{{ influxdb_database }}"
      username: "{{ influxdb_username }}"
      password: "{{ influxdb_password }}"
