---
- name: Create user digitransit
  user:
    name: digitransit
    state: present
    createhome: yes
    shell: /bin/bash

- name: Install systemd files
  ansible.builtin.template:
    src: systemd/{{ item }}
    dest: /etc/systemd/system/
  with_items:
    - digitransit.service
  notify: Restart digitransit

- name: Start systemd units
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
    daemon_reload: yes
  with_items:
    - digitransit.service

