---
- name: Install base packages
  package:
    name:
      - apache2
      - libapache2-mod-md
    state: present

- name: Delete content & directory
  file:
    state: absent
    path: /etc/apache2/sites-enabled/000-default.conf

- name: Enable the Apache2 modules
  community.general.apache2_module:
    state: present
    name: "{{ item }}"
    ignore_configcheck: True
    force: True
  with_items:
    - headers
    - ssl
    - http2
    - rewrite
    - md
    - proxy
    - proxy_http
    - proxy_wstunnel
  notify: Restart apache

- name: Install systemd files
  template: src=systemd/{{ item }} dest=/etc/systemd/system/
  with_items:
    - apache-reload.service
    - apache-reload.timer

- name: Start apache-reload.timer
  systemd:
    name: apache-reload.timer
    state: started
    enabled: yes
    daemon_reload: yes
