---
- name: Create mosquitto conf directory
  file:
    path: /etc/mosquitto/
    state: directory
    owner: root
    group: root

- name: Install mosquitto config files
  template:
    src: '{{ item }}'
    dest: /etc/mosquitto/
  with_items:
    - mosquitto.conf
    - mosquitto.acl
    - mosquitto.passwd
  notify: Restart mosquitto

- name: Install systemd files
  template: src={{ item }} dest=/etc/systemd/system/
  with_items:
    - mosquitto.service
    - gtfsrt2mqtt.service
  notify:
    - Restart mosquitto
    - Restart gtfsrt2mqtt

- name: Start services
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
    daemon_reload: yes
  with_items:
    - mosquitto.service
    - gtfsrt2mqtt.service

- name: Caddyfile
  ansible.builtin.template:
    src: mqtt.caddy
    dest: /etc/caddy/
    owner: caddy
    group: caddy
    mode: 0660
  notify: Restart caddy