---

- name: Add backports repo
  apt_repository:
    repo: "deb http://deb.debian.org/debian bullseye-backports main contrib non-free"
    state: present
    update_cache: yes

- name: Install packages
  apt:
    state: latest
    default_release: bullseye-backports
    name:
      - dbus-user-session
      - crun
      - uidmap
      - slirp4netns
      - podman

- name: Install systemd files for podman-prune
  template: src={{ item }} dest=/etc/systemd/system/
  with_items:
    - podman-prune.service
    - podman-prune.timer

- name: Start podman-prune.timer
  systemd:
    name: podman-prune.timer
    state: started
    enabled: yes
    daemon_reload: yes
