---
- name: Install Debian/Ubuntu-specific packages
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  ansible.builtin.package:
    state: latest
    name:
      - dbus-user-session
      - uidmap

- name: Install packages
  ansible.builtin.package:
    state: latest
    name:
      - crun
      - slirp4netns
      - podman

- name: Install systemd files for podman-prune
  template: src={{ item }} dest=/etc/systemd/system/
  with_items:
    - podman-prune.service
    - podman-prune.timer

- name: Start podman-prune.timer
  systemd:
    name: podman-prune.timer
    state: started
    enabled: true
    daemon_reload: true

- name: Login to container registry and create /etc/containers/auth.json
  containers.podman.podman_login:
    username: "{{ item.username }}"
    password: '{{ item.password }}'
    registry: "{{ item.registry }}"
    authfile: "{{ podman_auth_file }}"
  with_items: "{{ podman_authorized_repos }}"
  when: podman_authorized_repos is defined
  no_log: true

- name: Change permissions of auth file
  ansible.builtin.file:
    path: "{{ podman_auth_file }}"
    state: file
    mode: '0755'
  when: podman_authorized_repos is defined

- name: Create users
  user:
    name: "{{ item }}"
    create_home: True
    shell: /bin/bash
    state: present
  with_items: "{{ podman_prune_users }}"

- name: Enable lingering
  ansible.builtin.command:
    cmd: "loginctl enable-linger {{ item }}"
    creates: "/var/lib/systemd/linger/{{ item }}"
  with_items: "{{ podman_prune_users }}"

- name: Set custom container storage location
  template:
    src: storage.conf
    dest: /etc/containers/
  when: podman_root_container_storage_dir is defined
