---
otp_port: 8080
otp_base_dir: "/var/otp"
otp_restart_time: "3:00"
otp_restart_after_graph_build: false
manual_download_gtfs_feeds: []
manual_osm_downloads: []

otp_jvm_opts: "-Xmx6G"
otp_graph_build_jvm_opts: "-Xmx6G"

## when does the graph build run, systemd calendar syntax
graph_build_calendar: "*-*-* 01:00:00"
