---
- name: Copy OTP config
  template:
    src: otp/{{ item }}
    dest: "{{ otp_base_dir }}/build/"
    owner: otp
    group: otp
  with_items:
    - otp-config.json
    - router-config.json
    - build-config.json
  notify: Start graph build

- name: Ensure build-config.json is not in latest folder
  ansible.builtin.file:
    path: "{{ otp_base_dir }}/latest/build-config.json"
    state: absent

- name: Start service
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
    daemon_reload: yes
  with_items:
    - otp.service

- name: Caddyfile
  ansible.builtin.template:
    src: templates/otp.caddy
    dest: /etc/caddy/
    owner: caddy
    group: caddy
    mode: 0660
  notify: Restart caddy
