---
- name: Install systemd files
  ansible.builtin.template:
    src: systemd/{{ item }}
    dest: /etc/systemd/system/
  with_items:
    - otp.service

- name: Start service
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
    daemon_reload: yes
  with_items:
    - otp.service

- name: Caddyfile
  ansible.builtin.template:
    src: templates/otp.caddy
    dest: /etc/caddy/
    owner: caddy
    group: caddy
    mode: 0660
  notify: Restart caddy
