---
- name: Install base packages
  package:
    name:
      - curl
    state: present

- name: Install systemd files
  template:
    src: systemd/{{ item }}
    dest: /etc/systemd/system/
  with_items:
    - photon-new.service

- name: Disable service
  systemd:
    state: stopped
    name: "{{ item }}"
    enabled: false
    daemon_reload: yes
  with_items:
    - photon-new.service
  when: not photon_new_enabled

- name: Enable service
  systemd:
    state: started
    name: "{{ item }}"
    enabled: true
    daemon_reload: yes
  with_items:
    - photon-new.service
  when: photon_new_enabled

- name: Caddyfile
  ansible.builtin.template:
    src: photon-new.caddy
    dest: /etc/caddy/
    owner: caddy
    group: caddy
    mode: 0660
  notify: Restart caddy
