---
- name: Install base packages
  package:
    name:
      - python3-psycopg2
    state: present

- name: Install base packages
  package:
    name:
      - python3-docker
    state: present

- name: Create photon config directory
  file:
    path: "{{ item }}"
    state: directory
    owner: nominatim
    group: nominatim
    mode: 0775
  with_items:
    - "{{ photon_data_dir }}"

- name: Install systemd files
  template: src={{ item }} dest=/etc/systemd/system/
  with_items:
    - photon.service
    - photon-update.service
    - photon-update.timer

- name: Install systemd files for photon-pelias-adapter
  template: src={{ item }} dest=/etc/systemd/system/
  with_items:
    - photon-pelias-adapter.service
  notify:
    - Restart photon-pelias-adapter

- name: Start nomimatim and photon services
  systemd: state=started name="{{ item }}" enabled=yes daemon_reload=yes
  with_items:
    - photon.service
    - photon-update.timer
    - photon-pelias-adapter.service
