---
- name: Install base packages
  package:
    name:
      - curl
    state: present

- name: Install systemd files
  template:
    src: systemd/{{ item }}
    dest: /etc/systemd/system/
  with_items:
    - photon.service
    - photon-update.service
    - photon-update.timer

- name: Install systemd files for photon-pelias-adapter
  template:
    src: systemd/{{ item }}
    dest: /etc/systemd/system/
  with_items:
    - photon-pelias-adapter.service
  notify:
    - Restart photon-pelias-adapter

- name: Start services
  systemd: state=started name="{{ item }}" enabled=yes daemon_reload=yes
  with_items:
    - photon.service
    - photon-pelias-adapter.service

- name: Disable updates
  systemd:
    state: stopped
    name: "{{ item }}"
    enabled: false
    daemon_reload: yes
  with_items:
    - photon-update.timer
  when: not photon_enable_updates

- name: Enable updates
  systemd:
    state: started
    name: "{{ item }}"
    enabled: false
    daemon_reload: yes
  with_items:
    - photon-update.timer
  when: photon_enable_updates

- name: Caddyfile
  ansible.builtin.template:
    src: photon.caddy
    dest: /etc/caddy/
    owner: caddy
    group: caddy
    mode: 0660
  notify: Restart caddy
