---
- name: Install base packages
  package:
    name:
      - python3-psycopg2
    state: present

- name: Create photon data directory
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0775
  with_items:
    - "{{ photon_data_dir }}"

- name: Create volume
  containers.podman.podman_volume:
    state: present
    name: photon-data
    options:
      - "device={{ photon_data_dir }}/data"

- name: Install systemd files
  template:
    src: systemd/{{ item }}
    dest: /etc/systemd/system/
  with_items:
    - photon.service
    - photon-update.service
    - photon-update.timer

- name: Install systemd files for photon-pelias-adapter
  template:
    src: systemd/{{ item }}
    dest: /etc/systemd/system/
  with_items:
    - photon-pelias-adapter.service
  notify:
    - Restart photon-pelias-adapter

- name: Start services
  systemd: state=started name="{{ item }}" enabled=yes daemon_reload=yes
  with_items:
    - photon.service
    - photon-update.timer
    - photon-pelias-adapter.service
