---
- name: Only run "apt update" if the last one is more than a week ago
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 604800

- name: Install base packages
  package:
    name:
      - htop
      - tree
      - neovim
      - cron-apt
      - ripgrep
      - autojump
      - jq
      - zsh
      - unzip
      - tar
      - sudo
    state: present

- name: Install global aliases
  template: src=alias.sh dest=/etc/profile.d/

- hostname:
    name: "{{ server_name }}"

- name: Add hostname to /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "127.0.0.1 {{ server_name }}"

- name: Set timezone
  timezone:
    name: '{{ timezone }}'

- name: Configure passwordless sudo
  ansible.builtin.copy:
    content: '%sudo ALL=(ALL) NOPASSWD: ALL'
    dest: /etc/sudoers.d/passwordless

- name: Create user and add to groups
  user:
    name: "{{ item.name }}"
    groups:
      - sudo
      - systemd-journal
    append: true
    state: present
    createhome: true
    shell: /bin/bash
  with_items: "{{ users }}"

- name: Set authorized keys from url
  when: item.keys_url is defined
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ item.keys_url }}"
  with_items: "{{ users }}"

- name: Set authorized keys from local file
  when: item.keys_file is defined
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ lookup('file', item.keys_file) }}"
  with_items: "{{ users }}"
