---
- name: Only run "apt update" if the last one is more than a week ago
  when: ansible_distribution == 'Debian'
  ansible.builtin.apt:
    update_cache: True
    cache_valid_time: 604800

- name: Install Centos-specific packages
  when: ansible_distribution == 'CentOS'
  package:
    name:
      - epel-release
    state: present

- name: Install Debian-specific packages
  when: ansible_distribution == 'Debian'
  package:
    name:
      - cron-apt
    state: present

- name: Install base packages
  package:
    name:
      - htop
      - tree
      - neovim
      - autojump
      - ripgrep
      - jq
      - unzip
      - tar
      - sudo
      - bash-completion
    state: present
    update_cache: True


- name: Install global aliases
  template: src=alias.sh dest=/etc/profile.d/

- name: Set a hostname
  ansible.builtin.hostname:
    name: "{{ server_name }}"

- name: Set timezone
  timezone:
    name: '{{ timezone }}'

- name: Configure passwordless sudo
  ansible.builtin.copy:
    content: '%wheel ALL=(ALL) NOPASSWD: ALL'
    dest: /etc/sudoers.d/passwordless

- name: Create user and add to groups
  user:
    name: "{{ item.name }}"
    groups:
      - wheel
      - systemd-journal
    append: true
    state: present
    createhome: true
    shell: /bin/bash
  with_items: "{{ users }}"

- name: Remove users
  ansible.builtin.user:
    name: "{{ item }}"
    state: absent
    remove: yes
  with_items: "{{ removed_users }}"

- name: Set authorized keys from url
  when: item.keys_url is defined
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ item.keys_url }}"
  with_items: "{{ users }}"

- name: Set authorized keys from local file
  when: item.keys_file is defined
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ lookup('file', item.keys_file) }}"
  with_items: "{{ users }}"

