---
- name: Create working dir directory
  file:
    path: "{{ tileserver_work_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0775

- name: Download and unzip fonts
  ansible.builtin.unarchive:
    src: https://github.com/klokantech/klokantech-gl-fonts/archive/refs/tags/v1.0.0.zip
    dest: "{{ tileserver_work_dir }}"
    remote_src: yes
    creates: "{{ tileserver_work_dir }}/klokantech-gl-fonts-1.0.0"

- name: Copy sprites
  ansible.builtin.copy:
    src: sprites
    dest: "{{ tileserver_work_dir }}"

- name: Copy unauthorized.png
  copy:
    src: unauthorized.png
    dest: /usr/share/nginx/html/

- name: Symlink fonts
  ansible.builtin.file:
    dest: "{{ tileserver_work_dir }}/fonts"
    src: klokantech-gl-fonts-1.0.0
    state: link

- name: Install config and script files
  template: src={{ item }} dest={{ tileserver_work_dir }}
  with_items:
    - streets.json
    - bicycle.json
    - satellite-overlay.json
    - tileserver-config.json
  notify: Restart tileserver

- name: Install systemd files
  template:
    src: "systemd/{{ item }}"
    dest: /etc/systemd/system/
  with_items:
    - tileserver.service
    - tileserver-restart.service
    - tileserver-restart.timer
  notify: Restart tileserver

- name: Start tileserver and restart every night
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
    daemon_reload: yes
  with_items:
    - tileserver.service
    - tileserver-restart.timer

- name: Caddyfile
  ansible.builtin.template:
    src: templates/caddy/tileserver.caddy
    dest: /etc/caddy/
    owner: caddy
    group: caddy
    mode: 0660
  notify: Restart caddy

- name: Create tile cache dir
  file:
    path: "{{ tileserver_work_dir }}/nginx-cache/"
    state: directory
    owner: root
    group: root
    mode: 0775

- name: Install nginx
  package:
    name:
      - nginx

- name: Remove nginx default config
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: "Restart nginx"

- name: Install nginx config
  template:
    src: "nginx/tileserver-cache.conf"
    dest: /etc/nginx/sites-enabled/
  notify: "Restart nginx"
